### ISSUE TITLE
Bot crashes if a message is sent in a channel made after the bot is created

### ISSUE THREAD

**Issue by twisttaan** [TeamAilurus/ailurus#25]
## Error
```
Error: Cannot reply to a message that does not have a channel.
at Message.reply (/usr/src/app/node_modules/ailurus/src/structures/Message.ts:24:28)
at PingCommand.exec (/usr/src/app/src/commands/general/ping.ts:15:18)
at CommandHandler.handle (/usr/src/app/src/CommandHandler.ts:80:12)
at Client.<anonymous> (/usr/src/app/src/CommandHandler.ts:67:9)
at Client.emit (node:events:390:28)
at WebSocket.<anonymous> (/usr/src/app/node_modules/ailurus/src/client/ws/Gateway.ts:82:20)
at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:199:18)
at WebSocket.emit (node:events:390:28)
at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:1137:20)
at Receiver.emit (node:events:390:28)
```

We need a live-updating cache sort of system.

**Comment by megatank58** [comment]
This is most probably a cache bug and we can fix this by caching the channels on channel create/guild create

**Comment by Nciklol** [comment]
Yeah, we don't cache any new guilds. Looks like you should be able to move the code that caches the guild outside the if statement without any problems (?)

Also make sure to setup the CHANNEL_CREATE event, make sure to use the api types and be careful about DM channels (they will not have a guild, which channel currently requires.)

I can PR a fix in a few hours or someone can feel free to snipe it.
